import reducer from '../reducer';
import { addBoard, removeBoard, renameBoard } from '../actionCreators';
import { List, fromJS } from 'immutable';

describe('tabsReducer', () => {
    describe('ADD_BOARD', () => {
        it('Adds a new tab with a default name - "New Board"', () => {
            const state = List()
            const newState = reducer(state, addBoard())

            const expected = 'New Board';
            const actual = newState.getIn([0, 'name']);

            expect(actual).toEqual(expected)
        });

        it('Adds a new tab with an empty list of webtiles', () => {
            const state = List()
            const newState = reducer(state, addBoard())

            const expected = List();
            const actual = newState.getIn([0, 'webtiles']);

            expect(actual).toEqual(expected)
        })

        it('Adds a new tab with an id generated by uuid', () => {
            const state = List()
            const newState = reducer(state, addBoard())

            const id = newState.getIn([0, 'id']);

            expect(id).toBeDefined()
        })
    })

    describe('REMOVE_BOARD', () => {
        it('Removes the tab', () => {
            const remainingBoardName = 'New Board'
            const initialState = fromJS([
                {
                    name: 'Golan',
                    webtiles: []
                },
                {
                    name: remainingBoardName,
                    webtiles: []
                }
            ]);
            const newState = reducer(initialState, removeBoard(0))

            const actual = newState.getIn([0, 'name'])
            const expected = remainingBoardName;

            expect(newState.size).toEqual(1)
            expect(actual).toEqual(expected)
        })
    })

    describe('RENAME_BOARD', () => {
        it('Changes the name of the tab to the name in the action', () => {
            const state = fromJS([
                {
                    name: 'New Board',
                    webtiles: []
                }
            ]);
            const newName = 'Golan';
            const newState = reducer(state, renameBoard(0, newName));

            const expected = newName;
            const actual = newState.getIn([0, 'name']);

            expect(actual).toEqual(expected)
        })
    })
    
})